//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aria2 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aria2.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;__all_proxy_passwd&quot;:&quot;PASSWD设置__all_proxy的密码.标签:#http,#https,#ftp&quot;,&quot;__all_proxy_user&quot;:&quot;USER为__all_proxy设置用户.标签:#http,#https,#ftp&quot;,&quot;__all_proxy&quot;:&quot;PROXY对所有协议使用代理服务器.覆盖先前定义的代理,使用\&quot;\&quot;.您还可以覆盖此设置并指定a代理服务器为?褂玫奶囟ㄐ開_http_proxy,__https_proxy和__ftp_proxy选项.这会影响所有下载.可能的值:[http://][USER:PASSWORD@]HOST[:PORT]标签:#http,#https,#ftp&quot;,&quot;__allow_overwrite&quot;:&quot;[true|false]如果从头开始重新启动下载对应的控制文件不存在.看到也_自动文件重命名选项.可能的值:true,false默认值:false标签:#advanced,#file&quot;,&quot;__allow_piece_length_change&quot;:&quot;[true|false]如果给出false,aria2中止当长度不同时下载一个在控制文件中.如 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string explains {
            get {
                return ResourceManager.GetString("explains", resourceCulture);
            }
        }
    }
}
